### ISSUE TITLE
Gmsh (tracking maintainers and repos)

### ISSUE THREAD

**Issue by luzpaz** [luzpaz/FreeCAD-dependencies#21]
Per #20 there is a need to have Gmsh up to date and more established in the package ecosystem. 

<a href="https://repology.org/metapackage/gmsh/versions">
    <img src="https://repology.org/badge/vertical-allrepos/gmsh.svg" alt="Packaging status" align="right"></a>

## 4.0.7

- [x] FreeBSD [Downstream ticket](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233618)
- [x] Homebrew [Downstream ticket](https://github.com/Homebrew/homebrew-core/pull/34535)
- [x] Linuxbrew  
- [x] nixpkgs unstable [Downstream PR](https://github.com/NixOS/nixpkgs/pull/52042)
- [ ] Debian  
- [ ] Ubuntu  
- [x] Void Linux [Downstream ticket](https://github.com/void-linux/void-packages/issues/5606)
- [ ] vcpkg [Downstream ticket](https://github.com/Microsoft/vcpkg/issues/4930)

**Comment by luzpaz** [comment]
- [ ] FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233618

**Comment by luzpaz** [comment]
CC @kkremitzki just giving you a heads up about this ticket

**Comment by luzpaz** [comment]
## 4.1.0 
- [x] AUR  
- [ ] Fedora Rawhide  
- [ ] FreeBSD [Downstream ticket](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235037)  
- [x] VoidLinux [Downstream ticket](https://github.com/void-linux/void-packages/issues/5606)

**Comment by luzpaz** [comment]
## 4.1.2
- [ ] AUR
- [x] Void linux

**Comment by luzpaz** [comment]
## 4.1.3
- [x] AUR
- [x] Homebrew
- [ ] Linuxbrew
- [x] Macports
- [x] Void linux

**Comment by luzpaz** [comment]
Looks like there is better widespread adoption. Not surprising that Debian and Ubuntu are behind though. Closing for now.
