### ISSUE TITLE
CalculiX (tracking maintainers and repos)

### ISSUE THREAD

**Issue by luzpaz** [luzpaz/FreeCAD-dependencies#30]
Homepage: http://www.calculix.de
<a href="https://repology.org/metapackage/calculix-ccx/versions">
    <img src="https://repology.org/badge/vertical-allrepos/calculix-ccx.svg?header=CalculiX-ccx" alt="Packaging status" align="right">
</a>
- [x] AUR [Downstream Package](aur.archlinux.org/packages/calculix/)
- [ ] Arch
- [x] FreeBSD [Downsteam ticket](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234146)  
- [ ] Gentoo [Downstream ticket](https://bugs.gentoo.org/672548)   
- [ ] Homebrew  
- [ ] Linuxbrew  
- [x] OpenSUSE
- [x] Debian  
- [ ] Ubuntu
- [ ] OpenMandriva Cooker [Downstream ticket](https://github.com/OpenMandrivaAssociation/distribution/issues/2427)  
- [ ] Void Linux [Downstream ticket](https://github.com/void-linux/void-packages/issues/5603)
- [ ] vcpkg [Downstream ticket](https://github.com/Microsoft/vcpkg/issues/4929)  
- [x] nixpkgs [Dowstream ticket](https://github.com/NixOS/nixpkgs/issues/52479)

Ref: #20

**Comment by luzpaz** [comment]
@kkremitzki just wondering if this is on your radar to add v2.19 to debian unstable?
