### ISSUE TITLE
IfcOpenShell (tracking maintainers and repos)

### ISSUE THREAD

**Issue by luzpaz** [luzpaz/FreeCAD-dependencies#33]
<a href="https://repology.org/project/ifcopenshell/versions">
    <img src="https://repology.org/badge/vertical-allrepos/ifcopenshell.svg" alt="Packaging status" align="right">
</a>

- [ ] FreeBSD [Downstream ticket](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243007)
- [ ] Mageia Cauldron [Downstream ticket](https://bugs.mageia.org/show_bug.cgi?id=23948)
- [ ] Macports [testing](https://github.com/Schamschula/macports/commit/e7bb42f43c08d8edb29338c08bf311d84b3ebc31)
- [ ] Void [downstream ticket](https://github.com/void-linux/void-packages/issues/17942)
